Feature/ai 175 automatic and manual renumber
ENGworks-DEV/RenumberParts pull request #14
Opened 2020-09-24 16:20 UTC by PuertolasEngworks

Added automatic renumber
Redesign UI

2020-09-24 16:26 UTC, pabloderen requested changes

2020-09-24 16:26 UTC, pabloderen commented on RenumberParts_Shared/Core/RenumberMain.cs
> +                //Category cat = elem.Category;
Remove commented code

2020-09-24 16:26 UTC, pabloderen commented on RenumberParts_Shared/Core/RenumberMain.cs
> +        public static bool filterParam(Element elementEx, Element elementExP, BuiltInParameter param01, BuiltInParameter param02,
Camel case Method

2020-09-24 16:26 UTC, pabloderen commented on RenumberParts_Shared/Views/MainForm.xaml
> +        mc:Ignorable="d" Height="385.667" Width="280" MinHeight="442" MinWidth="280"  MaxHeight="430" MaxWidth="280" WindowStartupLocation="CenterScreen"
Round size to neares 100 or 50 px

2020-09-24 17:04 UTC, pabloderen requested changes

2020-09-24 17:04 UTC, pabloderen commented on RenumberParts_Shared/Views/MainForm.xaml.cs
> +        private int getElementConected(ref Element elem)
Change name to **getElementConnected**

2020-09-24 17:04 UTC, pabloderen commented on RenumberParts_Shared/Views/MainForm.xaml.cs
> +            //ConnectorSet connectors = this.getConnectorSetFromElement(elem);
Remove commented code

2020-09-24 17:04 UTC, pabloderen commented on RenumberParts_Shared/Views/MainForm.xaml.cs
> +            Connector CurrentConnector = null;
Variable not being used

2020-09-24 17:04 UTC, pabloderen commented on RenumberParts_Shared/Views/MainForm.xaml.cs
> +            List<string> categorias = new List<string>(new string[] { "OST_CableTrayFitting", "OST_CableTray", "OST_ConduitFitting", "OST_Conduit", "OST_DuctFitting", "OST_DuctCurves", "OST_DuctAcces
Change to categories

2020-09-28 14:02 UTC, ENGworks-DEV requested changes, later dismissed

2020-09-28 14:02 UTC, ENGworks-DEV commented on RenumberParts_Shared/Views/ColorForm.xaml.cs
> +        public ColorForm()
This does something?

2020-09-28 15:36 UTC, pabloderen approved these changes

2020-09-28 15:37 UTC, merged